#pragma once
#include <QString>

// RFC 5438 IMDN (Instant Message Disposition Notification) diagnostics info.
struct ImdnInfo
{
    // RFC 5438 §5.1 defines delivered/failed/forbidden (delivery-notification)
    // and displayed/error (display-notification); "processed" is an
    // extension status (e.g. RCS) some peers emit. Forbidden/Processed are
    // parsed (Task W096) but not generated by this client.
    enum class Disposition { None, Delivered, Displayed, Failed, Error, Forbidden, Processed };

    bool        present{false};
    Disposition disposition{Disposition::None};
    QString     messageId;
    QString     originalRecipient;
    QString     finalRecipient;

    static QString dispositionToString(Disposition d)
    {
        switch (d) {
        case Disposition::Delivered:  return QStringLiteral("delivered");
        case Disposition::Displayed:  return QStringLiteral("displayed");
        case Disposition::Failed:     return QStringLiteral("failed");
        case Disposition::Error:      return QStringLiteral("error");
        case Disposition::Forbidden:  return QStringLiteral("forbidden");
        case Disposition::Processed:  return QStringLiteral("processed");
        case Disposition::None:       break;
        }
        return QStringLiteral("none");
    }
};
